#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
server:
  port: ${serverPort}
  servlet:
    context-path: /${rootArtifactId}

spring:
  application:
    name: ${rootArtifactId}
  datasource:
    url: jdbc:mysql://${datasourceUrl}/${datasourcePrefix}-${rootArtifactId}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${datasourceUsername}
    password: ${datasourcePassword}
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    baseline-on-migrate: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
